# Generated by Django 3.2.3 on 2021-05-29 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topic_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'permissions': (('can_view_private_topics', 'Can view private Topics'),)},
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_from_topic', to='forum.topic'),
        ),
    ]
