# Generated by Django 3.2.3 on 2021-05-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210529_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_delete_every_post', 'Can delete every post'),)},
        ),
    ]
