# Generated by Django 3.2.3 on 2021-05-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('forum', '0005_auto_20210530_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowed_users', to='auth.Group'),
        ),
    ]
