# Generated by Django 3.2.3 on 2021-05-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20210530_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
