# Generated by Django 3.2.3 on 2021-05-29 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0008_topic_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
