# Generated by Django 3.2.3 on 2021-05-29 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_topic_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'permissions': (('can_verify_topics', 'Can verify topics'), ('can_view_all_topics', 'Can view all topics'))},
        ),
    ]
