# Generated by Django 3.2.3 on 2021-05-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20210530_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_delete_every_post', 'Can delete every post'),)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'permissions': (('can_verify_topics', 'Can verify topics'), ('can_view_all_topics', 'Can view all topics'))},
        ),
    ]
