# Generated by Django 3.2.3 on 2021-05-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20210530_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_delete_every_post', 'Can delete every post'), ('can_delete_own_post', 'Can delete own post'))},
        ),
    ]
