# Generated by Django 3.2.3 on 2021-05-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_delete_every_post', 'Can delete every post'), ('can_delete_own_post', 'Can delete own post'), ('can_add_posts', 'Can add posts'))},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'permissions': (('can_verify_topics', 'Can verify topics'), ('can_view_all_topics', 'Can view all topics'), ('can_add_topics', 'Can add topics'))},
        ),
    ]
